
//AWS 
const AWS_ACCESS_KEY_ID='1234567890'
const AWS_SECRET_ACCESS_KEY='ABCDEFGHIJKLMN'
const AWS_DEFAULT_REGION='us-east-1'
const AWS_DEFAULT_OUTPUT='json'

const AWS_ACCOUNT_ID='1234567890'
const AWS_REGION=AWS_DEFAULT_REGION

//repo location
const ROOT='/healthylinkx-lex'

//datastore user
const DBUSER='user'
const DBPWD='123456'

exports.AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID;
exports.AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY;
exports.AWS_DEFAULT_REGION=AWS_DEFAULT_REGION;
exports.AWS_DEFAULT_OUTPUT=AWS_DEFAULT_OUTPUT;
exports.AWS_ACCOUNT_ID=AWS_ACCOUNT_ID;
exports.AWS_REGION=AWS_REGION;

exports.ROOT=ROOT;

exports.DBUSER=DBUSER;
exports.DBPWD=DBPWD;
